title: PikaPods Docs
description: Notes on selected apps and PikaPods controls
baseurl: ""
url: "https://docs.pikapods.com"

permalink: pretty
include: ["_redirects"]
exclude: ["README.md", "Rakefile"]

search_enabled: true
heading_anchors: true

aux_links:
  "Simple Open Source App Hosting":
    - "https://www.pikapods.com"

theme: just-the-docs
color_scheme: pikapods
kramdown:
  toc_levels: 1..3

plugins:
  - jekyll-seo-tag